config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get 'pages/index'
  get 'event_attendees/attend', to: 'event_attendees#attend'

  get 'users/create'
  get 'users/show', to: 'users#show'

  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  resources :users
  resources :events
  resources :event_attendees
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees

  scope :past, -> { where('date < ?', Time.now) }
  scope :upcoming, -> { where('date >= ?', Time.now) }
  scope :today, -> { where('date = ?', Date.today) }
end

app/models/event_attendee.rb
# frozen_string_literal: true

class EventAttendee < ApplicationRecord
  belongs_to :attended_event, class_name: 'Event'
  belongs_to :attendee, class_name: 'User'

  validates :attendee_id, presence: true
  validates :attended_event_id, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include EventsHelper
  has_many :events, foreign_key: 'creator_id', dependent: :destroy
  has_many :event_attendees, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendees

  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/event_attendees_controller.rb
# frozen_string_literal: true

class EventAttendeesController < ApplicationController
  def attend
    @event = Event.find(params[:id]).attendees << current_user
    flash[:success] = 'You are attending this event!'
    redirect_to users_show_url
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  before_action :logged_in?, only: %i[create destroy]

  def index
    @event = if params[:filter] == 'user'
               current_user.events # user ID here
             else
               Event.all
             end
  end

  def new
    @event = Event.new
  end

  def show
    @event = Event.find(params[:id])
    @list = @event.attendees
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      flash[:success] = 'Your Event has been created!'
      redirect_to users_show_url
    else
      render 'new'
    end
  end

  def destroy; end

  private

  def event_params
    params.require(:event).permit(:title, :location, :date, :description)
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def index
    @event = Event.all
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_to users_show_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :restrict_access, only: %i[index show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.now[:success] = 'Welcome to Micro Eventbrite!'
      log_in(@user)
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(current_user.id)
    @events = @user.events
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def restrict_access
    redirect_to login_path unless current_user
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/event_attendees_helper.rb
# frozen_string_literal: true

module EventAttendeesHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
  def created_events(user)
    render(user.events)
  end

  def upcoming(user)
    render(user.attended_events.upcoming)
  end

  def past(user)
    render(user.attended_events.past)
  end
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: 'gravatar')
  end
end

app/views/events/_display.html.erb
<% @event.each do |event|  %>
<div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <div class="well well-lg">
          <h3>Title: <%= link_to event.title, event %></h3>
          <h4>Location: <%= event.location %></h4>
          <h4>Date: <%= event.date %></h4>
          <h4>Description: <%= event.description %></h4>
          <% if current_user %>
            <% if :button && event.creator != current_user && current_user.attended_events.find_by(id: event.id).nil? && event.date >= Date.today %>
              <%= link_to "Attend this event", event_attendees_attend_path(id: event.id),  class: 'btn btn-primary' %>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/events/_event.html.erb
<h3>Title: <%= event.title %></h3>
<h4>Location: <%= event.location %> </h4>
<h4>Date: <%= event.date %></h4>
<p>Description: <%= event.description %> </p>
<hr>

app/views/events/new.html.erb
<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@event, url: events_path) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title , class: 'form-control' %>

      <%= f.label :location %>
      <%= f.text_field :location , class: 'form-control' %>

      <%= f.label :date %>
      <%= f.date_select :date, placeholder: "mm/dd/yyyy" %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Create Event", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/events/show.html.erb
<h1>Attendees of <%= @event.title %></h1>


<div class="container">
  <div class="col-md-6 col-md-offset-3">
    <ul>
      <% if @list.count > 0 %>
        <% @list.each do |f|%>
            <li> <%= f.name %> (<%= f.email %>)</li>
        <% end %>
      <% else %>
        NO ATTENDEES
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "EventBrite", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <% if logged_in? %>
          <li><%= link_to "My Events", users_show_url %></li>
          <li><%= link_to "Create Event", new_event_path %></li>
          <li><%= link_to "Log out", logout_path, method: 'delete' %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Micro EventBrite</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%#= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/pages/Index.html.erb
<h1>Welcome to EventBrite</h1>
<h2>You can see all the Events here</h2>
<div class="row">
  <div class="col-md-12">
    <%= render 'events/display' %>
  </div>
</div>

app/views/pages/index.html.erb
<h1>Welcome to EventBrite</h1>
<h2>You can see all the Events here</h2>
<div class="row">
  <div class="col-md-12">
    <%= render 'events/display' %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(@user, url: signup_url) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name , class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h3>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h3>
    </section>
  </aside>

  <aside class="col-md-6">
    <section class="user_info">
      <% if @user.events.any? %>
        <h3>Created <%= @user.events.count %> events </h3>
        <ul class="media-list">
          <%= created_events(@user) %>
        </ul>
      <% end %>
    </section>

    <section class="user_info">
      <h2>Upcoming Events</h2>
        <ul class="media-list">
          <%= upcoming(@user) %>
        </ul>
    </section>

    <section class="user_info">
    <h2>Past Events</h2>
        <ul class="media-list">
        <%= past(@user) %>
        </ul>
    </section>
  </aside>
</div>